/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISmartAccount,
  ISmartAccountInterface,
} from "../../../../src/contracts/AgentSmartAccountFactory.sol/ISmartAccount";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "enableModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISmartAccount__factory {
  static readonly abi = _abi;
  static createInterface(): ISmartAccountInterface {
    return new utils.Interface(_abi) as ISmartAccountInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISmartAccount {
    return new Contract(address, _abi, signerOrProvider) as ISmartAccount;
  }
}
