version: '3.8'

services:
  api:
    build: .
    container_name: agent-dao-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - ./logs:/usr/src/app/logs
    command: node dist/index.js
    networks:
      - agent-dao-network

  dashboard:
    build: .
    container_name: agent-dao-dashboard
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    volumes:
      - ./logs:/usr/src/app/logs
    command: node dashboard-server.js
    networks:
      - agent-dao-network

  # Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: agent-dao-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - api
      - dashboard
    networks:
      - agent-dao-network

networks:
  agent-dao-network:
    driver: bridge 